terminal_options:
  width: 80
  height: 40
  title: roguelike
  mode: tiles
  tile_name: tileset13
  tile_size: 13
  font_name: teko
  font_size: 12
  min_font_size: 8
  max_font_size: 18


map_options:
  width: 128
  height: 128
