required_components:
  - position


entity_prefabs:

  player:
    player:
    sprite:
      char: '@'
      color: '#ffffffff'
    physical:
    creature:
      sight: 20


  mutant:
    npc:
      ai: mutant
    sprite:
      char: 'M'
      color: '#ffff8888'
    physical:
    creature:
      sight: 16
