entity_require:
  - position


entity_prefabs:

  player:
    position:
    player:
    sprite:
      :char: '@'
      :color: '#ffffffff'
    creature:
      :sight: 20


  mob:
    position:
    npc:
    sprite:
      :char: 'M'
      :color: '#ffff8888'
    creature:
      :sight: 16
