required_components:
  - position


entity_prefabs:

  player:
    player:
    sprite:
      char: '@'
      color: '#ffffffff'
    creature:
      sight: 20


  mob:
    npc:
    sprite:
      char: 'M'
      color: '#ffff8888'
    creature:
      sight: 16
